version: "3.9"

services:
  backend:
    build: .
    container_name: auto_center_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=auto_center
      - POSTGRES_USER=auto_user
      - POSTGRES_PASSWORD=auto_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=1
      - SECRET_KEY=supersecretkey123!@#
    volumes:
      - ./staticfiles:/code/staticfiles

  db:
    image: postgres:15
    container_name: auto_center_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auto_center
      POSTGRES_USER: auto_user
      POSTGRES_PASSWORD: auto_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: