#!/bin/sh
set -e

echo "⏳ Ожидание готовности PostgreSQL..."
while ! python -c "import socket; socket.create_connection(('db', 5432), timeout=1)" 2>/dev/null; do
  echo "  → PostgreSQL ещё не готов, ждём..."
  sleep 2
done
echo "✅ PostgreSQL готов"

echo "🛠 Проверяем миграции..."
if ! python manage.py showmigrations pc 2>/dev/null | grep -q '\[X\]'; then
  echo "  → Миграции отсутствуют — создаём вручную"
  
  # Создаём папку миграций, если нет
  mkdir -p pc/migrations
  touch pc/migrations/__init__.py

  # Генерируем пустую миграцию
  python manage.py makemigrations pc --empty --name initial --verbosity 0

  # Подменяем её на полную (гарантированно рабочую)
  cat > pc/migrations/0001_initial.py << 'EOF'
# Generated by Django on 2025-12-19 — for Vanessa's PC Configurator
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('socket', models.CharField(blank=True, max_length=100)),
                ('chipset', models.CharField(blank=True, max_length=50)),
                ('ram_type', models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=20)),
                ('has_pcie', models.BooleanField(default=False)),
                ('power_consumption', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('admin', 'Администратор')], default='guest', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'abstract': False},
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.user')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='BuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.build')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pc.component')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='PresetBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target', models.CharField(choices=[('gaming', 'Игры'), ('office', 'Офис'), ('streaming', 'Стриминг'), ('budget', 'Бюджет')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to...', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
EOF

  echo "🔧 Применяем миграции впервые..."
  python manage.py migrate --noinput
else
  echo "  → Миграции уже применены"
fi

echo "📦 Загружаем компоненты и пресеты (если ещё не загружены)..."
python manage.py shell << 'EOF'
from pc.models import Component, PresetBuild

# Компоненты (идемпотентно — не дублируются)
components = [
    ("Intel Core i5-13600K", "CPU", 25000, "14 ядер, 5.1 ГГц", "LGA1700", "B760", "", False, 181),
    ("AMD Ryzen 5 7600", "CPU", 18000, "6 ядер, AM5", "AM5", "", "", False, 65),
    ("Intel Core i3-13100", "CPU", 10000, "4 ядра, бюджетный", "LGA1700", "", "", False, 60),
    ("ASUS ROG Strix B760-G", "Материнская плата", 18000, "LGA1700, DDR5", "LGA1700", "B760", "DDR5", True, 0),
    ("MSI PRO B650M-A", "Материнская плата", 15000, "AM5, DDR5", "AM5", "B650", "DDR5", True, 0),
    ("Gigabyte H610M H", "Материнская плата", 7000, "LGA1700, DDR4", "LGA1700", "H610", "DDR4", True, 0),
    ("Kingston Fury Beast 32 ГБ (2×16)", "ОЗУ", 12000, "DDR5, 6000 МГц", "", "", "DDR5", False, 5),
    ("Crucial 16 ГБ DDR5", "ОЗУ", 6000, "DDR5, 5200 МГц", "", "", "DDR5", False, 3),
    ("ADATA 8 ГБ DDR4", "ОЗУ", 3000, "DDR4, 3200 МГц", "", "", "DDR4", False, 2),
    ("NVIDIA GeForce RTX 4070", "GPU", 65000, "12 ГБ VRAM", "", "", "", True, 200),
    ("Samsung 980 Pro 1 ТБ", "SSD", 10000, "NVMe, PCIe 4.0", "", "", "", False, 6),
    ("Samsung 970 EVO 500 ГБ", "SSD", 5000, "NVMe, PCIe 3.0", "", "", "", False, 5),
    ("Kingston A400 480 ГБ", "SSD", 2500, "SATA III", "", "", "", False, 3),
    ("Corsair RM850e", "БП", 9000, "850 Вт, Gold", "", "", "", False, 0),
    ("Cooler Master MWE 550", "БП", 5000, "550 Вт, Bronze", "", "", "", False, 0),
    ("DeepCool DN450", "БП", 3000, "450 Вт", "", "", "", False, 0),
    ("DeepCool AK620", "Охлаждение", 5000, "Башенный кулер", "LGA1700,AM4,AM5", "", "", False, 0),
]

# Проверка длины (удали после отладки)
assert all(len(c) == 9 for c in components), "Ошибка: не все кортежи длины 9"

print("Проверяем длину первого кортежа:", len(components[0]))
for i, comp in enumerate(components):
    if len(comp) != 9:
        print("Ошибка в компоненте", i, ":", comp, "— длина =", len(comp))

for name, cat, price, desc, sock, chip, ram, pcie, power in components:
    obj, created = Component.objects.get_or_create(
        name=name,
        defaults={
            'category': cat,
            'price': price,
            'description': desc,
            'socket': sock,
            'chipset': chip,
            'ram_type': ram,
            'has_pcie': pcie,
            'power_consumption': power,
        }
    )
    if created:
        print("  ➕", name)

# Пресеты
presets = [
    ("Игровая 2025", "Для игр в 1440p", "gaming"),
    ("Офисная база", "Для работы и Zoom", "office"),
    ("Бюджетная", "Для учёбы и интернета", "budget"),
]

for name, desc, target in presets:
    obj, created = PresetBuild.objects.get_or_create(
        name=name,
        defaults={'description': desc, 'target': target}
    )
    if created:
        print("  🎯", name)

print("✅ Компоненты и пресеты готовы")
EOF

echo "👑 Проверяем суперпользователя..."
python manage.py shell << EOF
import os
from django.contrib.auth import get_user_model
User = get_user_model()
username = os.getenv('ADMIN_USER', 'admin')
email = os.getenv('ADMIN_EMAIL', 'admin@example.com')
password = os.getenv('ADMIN_PASSWORD', 'secureadmin123')

if not User.objects.filter(username=username).exists():
    User.objects.create_superuser(username=username, email=email, password=password, role='admin')
    print("✅ Суперпользователь создан:", username)
else:
    print("♻️ Суперпользователь уже существует")
EOF

echo "🚀 Запускаем Gunicorn..."
exec gunicorn pc_config.wsgi:application --bind 0.0.0.0:8000 --workers 2